version: "3"

services:  
  front:
    container_name: front
    build: ./frontend
    ports:
      - 3000:80
    depends_on: 
      - db
      - api

  api:
    container_name: api
    build: ./api
    ports:
      - 7000:80
    depends_on:
      - db

  seed:
    container_name: seed
    build: ./mongo-config
    links:
      - db

  db:
    container_name: mongodb
    image: mongo 
    ports: 
      - 27017:27017
    volumes:
     - ./mongo-data:/data/db
#     - ./mongo-config:/scripts
  