version: "3"

services:  
  agenda-api:
    container_name: agd-api
    build: .
    ports:
      - 7000:80
    depends_on:
      - db
    
  db:
      image: mongo     
      ports: 
      - 27017:27017
  