version: "3"

services:  
  agenda-api:
    container_name: agd-api
    build: ./api
    ports:
      - 7000:80
    depends_on:
      - db
    
  db:
    container_name: mongodb
    image: mongo     
    ports: 
    - 27017:27017
  